import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'errors/index': 'src/errors/index.ts',
    'template-extras/index': 'src/template-extras/index.ts',
    'versioning/index': 'src/versioning/index.ts',
    'testing/index': 'src/testing/index.ts',
    'cost/index': 'src/cost/index.ts',
    'cost/tiktoken': 'src/cost/tiktoken.ts',
    'sources/index': 'src/sources/index.ts',
    'sources/http': 'src/sources/http.ts',
    'sources/fs': 'src/sources/fs.ts',
    'adapters/openai/index': 'src/adapters/openai/index.ts',
    'adapters/anthropic/index': 'src/adapters/anthropic/index.ts',
    'adapters/ai-sdk/index': 'src/adapters/ai-sdk/index.ts',
    'adapters/langchain/index': 'src/adapters/langchain/index.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  minify: false,
  treeshake: true,
  splitting: false,
  target: 'es2022',
  external: [
    'ai',
    'openai',
    '@anthropic-ai/sdk',
    '@langchain/core',
    'js-tiktoken',
    'node:fs',
    'node:fs/promises',
    'node:path',
  ],
  tsconfig: './tsconfig.build.json',
});
